### ISSUE TITLE
Display issues with New Twenty-One Theme

### ISSUE THREAD

**Issue by TheMrDrProf** [LithiumHosting/apnscp-whmcs#4]
First, want to say thanks for making this plugin public. It helps a ton!

I know WHMCS 8.1 JUST released, but wanted to post this anyways in case y'all hadn't seen it. Compared to the six theme, which works fine, the client area display is extremely messed up on the Twenty-One theme. Colors, borders, and gradients are all missing, and the quick icons are a mess. I zoomed out in the below screenshots to show the full page. Let me know if I can help in any way! Thank you!

![21](https://user-images.githubusercontent.com/25834380/103321672-6a5f0680-4a00-11eb-971d-1768b24d400f.png)
![212](https://user-images.githubusercontent.com/25834380/103321676-6f23ba80-4a00-11eb-9bd9-a6527dc222d0.png)

**Comment by tsiedsma** [comment]
The module is not compatible with the new theme based on the bootstrap changes.  
You're welcome to submit a PR, I won't likely update things until I start testing WHMCS 8.1 which won't be for a while.  I usually wait for my current version to near EOL and let them work out the inevitable patches to fix things that worked great prior to the update.

**Comment by tsiedsma** [comment]
Sorry for closing :) and thanks for the comment.  I'm happy to share my efforts if it helps expose more people to ApisCP.
This issue will be resolved in the near future if not sooner in a new branch for 8.1 support.

**Comment by TheMrDrProf** [comment]
No worries! I had figured it may not be soon. Well aware that 8.1 JUST came out. I am playing around with it, and have got a few things bootstrap compliant so far. The quick action icons are a pain in the butt to get switched, and try to maintain compatible code in for older themes and bootstrap. If I get everything working okay and confident enough in my code, I'll submit a PR.

**Comment by tsiedsma** [comment]
Resolved in version 1.0.11
